version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250"
    environment:
      - LOG_LEVEL=debug

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: [ --config=/etc/otel-collector-config.yaml ]
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 2s
      timeout: 5s
      retries: 15

  main:
    image: main-app:v0.0.1
    container_name: main-app
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - EXPORTER_TYPE=grpc
      - COLLECTOR_URL=otel-collector:4317
      - COLLECTOR_INSECURE=true
      - KAFKA_ADDRESS=broker:29092
      - KAFKA_TOPIC=test-topic
    ports:
      - "8080:8080"

  processor:
    image: processor-app:v0.0.1
    container_name: processor-app
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - EXPORTER_TYPE=grpc
      - COLLECTOR_URL=otel-collector:4317
      - COLLECTOR_INSECURE=true
      - KAFKA_ADDRESS=broker:29092
      - KAFKA_TOPIC=test-topic
      - EXECUTOR_BASE_PATH=/bin