version: "3.9"
services:
  main:
    image: main-app:v0.0.1
    container_name: main-app
    environment:
      - EXPORTER_TYPE=grpc
      - COLLECTOR_URL=otel-collector:4317
      - COLLECTOR_INSECURE=true
      - KAFKA_ADDRESS=broker:9092
      - KAFKA_TOPIC=test-topic
    ports:
      - "8080:8080"
    networks:
      - test
  processor:
    image: processor-app:v0.0.1
    container_name: processor-app
    environment:
      - EXPORTER_TYPE=grpc
      - COLLECTOR_URL=otel-collector:4317
      - COLLECTOR_INSECURE=true
      - KAFKA_ADDRESS=broker:9092
      - KAFKA_TOPIC=test-topic
    networks:
      - test

networks:
  test: