### Send POST request with json body
POST http://localhost:8080/data
Content-Type: application/json
X-Correlation-ID: 0ad1348f14031692

{
  "name": "test",
  "random": 5
}

### Ping
GET http://localhost:8080/ping